config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :pictures , only: [:index,:new,:edit,:destroy,:update,:create]
  root 'pictures#index'
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    if user && user.admin?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
    validates :title, :comment, :image_url, presence: true
    mount_uploader :image_url, ContentUploader
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
        
  has_many :pictures
  
  def self.create_unique_string
    SecureRandom.uuid
  end
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)
    if ! user 
      user = User.find_by(email: "#{auth.uid}-#{auth.provider}@example.com") 
    end
    
    unless user
      user = User.new(
        name: auth.extra.raw_info.name,
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        image_url: auth.info.image,
        password: Devise.friendly_token[0,20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # before_actionで下で定義したメソッドを実行
  before_action :configure_permitted_parameters, if: :devise_controller?

  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name)

  protected

    #deviseのストロングパラメーターにカラム追加するメソッドを定義
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    def index
        @pictures = Picture.all.order(:id)
        if user_signed_in?
          @username = current_user.name
        end
    end
    def new
        @picture = Picture.new
    end
    def create
        @picture = Picture.new(picture_params)
        @picture.user_id = current_user.id
        if @picture.save
          redirect_to pictures_path, notice: '投稿しました'
        else
            render 'new'
        end
    end
    def edit
        @picture = Picture.find(params[:id])
    end
    def update
        @picture = Picture.find(params[:id])
        if @picture.update(picture_params)
            redirect_to pictures_path, notice: '編集しました'
        else
            render 'edit'
        end
    end
    def destroy
        @picture = Picture.find(params[:id])
        @picture.destroy
        redirect_to pictures_path, notice: '削除しました'
    end
    private
      def picture_params
          params.require(:picture).permit(:title,:comment,:image_url)
      end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
        
        if @user.persisted?
            set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
            sign_in_and_redirect @user, event: :authentication
        else
            session["devise.facebook_data"] = request.env["omniauth.auth"]
            redirect_to new_user_registration_url
        end
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    def build_resource(hash=nil)
        hash[:uid] = User.create_unique_string
        super
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "TOP", root_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "新規投稿", new_picture_path %></li>
              <li><%= link_to "マイページ", edit_user_registration_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "ログイン", new_user_session_path %></li>
              <li><%= link_to "サインアップ", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

<%= yield %>
  <footer>
    <p>My Instagram 2017 Copyright K.M</p>
  </footer>
</body>
</html>

app/views/pictures/edit.html.erb
<div class="container"><div class="row"><div class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
<h1>投稿の編集</h1>

<%= form_for(@picture, url: picture_path, method: :patch) do |f| %>
  <!-- エラーがあった場合の表示 -->
  <% if @picture.errors.any? %>
    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  
  <%= f.label :title %>
  <%= f.text_field :title, class:"form-control", placeholder: 'title' %>
  <br>
  <%= f.label :comment %>
  <%= f.text_field :comment, class:"form-control", placeholder: "comment" %>
  <br>
  <%= image_tag @picture.image_url %>
  <br>
  <%= f.label :image_url %>
  <%= f.file_field :image_url %>
  <br>
  <%= f.submit '投稿', :class => "btn btn-primary" %>
  <%= link_to '戻る',:back, :class => 'btn btn-default' %>
<% end %>
</div></div></div>

app/views/pictures/index.html.erb
<% if notice != nil %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>
<section class="container-fluid">
  <div class="row"><div class="col-sm-1 col-md-2 col-lg-3"></div>
  <div class="col-sm-10 col-md-8 col-lg-6">
    <div class="top-logo"><%= image_tag "insta.png" %><br></div>
    <div class="row">
      <div class="your-name">
        <% if @username %>
            <%= link_to '新規投稿', new_picture_path, :class => 'btn btn-primary' %>
            こんにちは @<%= @username %> さん
        <% else %>
            ログインしていません
        <% end %>
      </div>
    </div><br>
    <table class="table table-bordered table-hover picture-area">
      <% @pictures.each do |picture| %>
        <tr><td>
          <div class="row">
            <div class="col-sm-6 picture-title">
              <%= picture.title %>
            </div>
            <div class="col-sm-6">
            </div>
            <div class="col-sm-12"><%= image_tag picture.image_url , :class => 'img img-rounded'%></div>
            <div class="col-sm-12 picture-comment"><br><%= picture.comment %><br><br></div>
            <% if picture.user == current_user %>
              <div class="col-sm-6 col-md-4 col-lg-3">
                <%= link_to '編集', edit_picture_path(picture.id), :class => 'btn btn-default'%>
                <%= link_to '削除', picture_path(picture.id), data: {confirm: 'delete this picture?' } , method: :delete, :class => 'btn btn-danger'%>
              </div>
            <% end %>
            <% if picture.user %>
              <div class="col-sm-6 col-md-4 col-lg-6 picture-name">
                @<%= picture.user.name %>さんの投稿
                <br><%= picture.created_at.strftime("%Y年%-m月%d日_%H:%M:%S") %>
              </div>
            <% end %>
            </div>
          </div></td>
        </tr>
      <% end %>
    </table>
  </div></div>
</section>

app/views/pictures/new.html.erb
<div class="container"><div class="row"><div class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
<h1>新規投稿</h1>
<%= form_for(@picture, url: pictures_path, method: :post) do |f| %>
  <!-- エラーがあった場合の表示 -->
  <% if @picture.errors.any? %>
    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  
  <!-- 入力フォーム -->
  <%= f.label :"タイトル" %>
  <%= f.text_field :title, class:"form-control", placeholder: 'title' %>
  <br>
  <%= f.label :"コメント" %>
  <%= f.text_field :comment, class:"form-control", placeholder: 'comment'  %>
  <br>
  <%= f.label :"写真を選択" %>
  <%= f.file_field :image_url %>
  <br>
  <%= f.submit '投稿', :class => "btn btn-primary" %>
  <%= link_to '戻る',:back, :class => 'btn btn-default' %>
<% end %>
</div></div></div>